---
 - name: Check admin.conf file exists.
   stat:
     path: /etc/kubernetes/admin.conf
   register: k8s_conf
 - name:
   block:
     - name: initialize the cluster
      #shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.2.4 >> cluster_initialized.txt
       shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.2.4 >> cluster_initialized.txt

       args:
        chdir: $HOME
        creates: cluster_initialized.txt

     - name: get join command
       shell: kubeadm token create --print-join-command
       register: join_command_raw

     - name: set join command
       set_fact:
         join_command: "{{ join_command_raw.stdout_lines[0] }}"
       delegate_to: "{{ item }}"
       delegate_facts: True
       with_items: "{{ groups['worker'] }}"

     - name: create .kube directory
       file:
         path: $HOME/.kube
         state: directory
         mode: 0755

     - name: copy admin.conf to user's kube config
       copy:
         src: /etc/kubernetes/admin.conf
         dest: $HOME/.kube/config
         remote_src: yes
   when: not k8s_conf.stat.exists 
 


